### ISSUE TITLE
[Bug] Using [centered] while viewing on a bedrock client is broken

### ISSUE THREAD

**Issue by realdoomsboygaming** [PandaaaPlays/AutomaticBroadcast#12]
Here is how the preview looks like while on a Java client.

![image](https://github.com/user-attachments/assets/4bdb0cf8-eb63-4537-a7b6-777f97785877)

This is how it looks on the default Bedrock client chat settings.

![image](https://github.com/user-attachments/assets/2493a3c3-94b2-45db-b2df-618658e57777)
 
Here is the config portion for this broadcast:
```

  homes:
    # A list of messages that will be displayed when the broadcast occurs.
    messages:
      - ""  
      - " [centered]  &x&f&b&3&3&3&3&lH&x&f&5&2&f&2&f&lO&x&f&0&2&a&2&a&lT&x&e&a&2&6&2&6&lD&x&e&5&2&1&2&1&lO&x&d&f&1&d&1&d&lG&x&d&9&1&9&1&9&lC&x&d&4&1&4&1&4&lR&x&c&e&1&0&1&0&lA&x&c&9&0&b&0&b&lF&x&c&3&0&7&0&7&lT"  
      - "[centered] &eUse &b/sethome&e and &b/home&e to create quick ways to teleport"
      - "[centered] &earound."
      - "[centered] &7We all hate losing our stuff."  
      - ""
    # What will occur when a player clicks on the broadcast :
    # "*" -> Suggests a message in the player's chat. (Ex.: *exemple -> Suggests "exemple")
    # "/" -> Suggests a command in the player's chat. (Ex.: /exemple -> Suggests "/exemple")
    # Anything else opens a link if IT IS VALID! (Make sure to add "https://...")
    click: "/homes"
    # The tooltip that will be displayed when the players hover over the message.
    hover:

    # The sound played for every player receiving the broadcast.
    # Please refer to the bukkit list of sounds : https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    sound:
    # The player(s) that should not receive this broadcast.
    exempted-players:
      - exempted-player1
      - exempted-player2
```
